### Some configurations
source_data_root: "/home/tiger/ws/CrossDevicePredict"
cutlass_path: "/home/tiger/cutlass"
target_kernel_type: "gemm"
# target_kernel_type: "conv2d_fprop"

source_gpu: "Tesla_V100-SXM2-32GB"
# source_gpu: "Tesla_T4"
# source_gpu: "A100_Graphics_Device"
target_gpu: "Tesla_V100-SXM2-32GB"
# target_gpu: "Tesla_T4"
# target_gpu: "A100_Graphics_Device"
dtype: "fp32"
# dtype: "fp16"
# target_model: "ResNet50"
# target_model: "BERT-Large"

cfg_name: mlp-large
metric_learner: 2
cost_model:
  input_layer_unit: 1024
  embedded_layers:
    - 1024
    - 1024
    - 1024
    - 1024
    - 1024
  embed_feature_len: 1024
  regression_layers:
    - 1024
    - 1024
    - 1024
    - 1024
  opt_type: "adam"
  lr: 1.e-6
  wd: 0.01
  batch_size: 128
  enable_similarity: False
  loss_type: MSE # one of MSE, MAPE, MSPE
  use_clip: null
  enable_up_sampling: False
  enable_adversarial: False
  use_residual: False
  lr_scheduler: "none"
  USE_CMD_REGULAR: False
  use_di: False
  dropout_rate: null

verify:
  CONTINUOUS_LEARN: False
  TARGET_TASK_ID: null
